### ISSUE TITLE
Settings view should have the same title always, not a movie name

### ISSUE THREAD

**Issue by carstenhag** [haroldadmin/MovieDB#6]
![screenshot_20190302-123725](https://user-images.githubusercontent.com/3776997/53681323-2efe2e80-3ce8-11e9-96ca-e25ee26241bd.jpg)
Right now, if you are inside a movie and go to the settings via the 3 dots, the settings view's title is now the movies title.

If you decide to remove the dots on the movies like I wrote in #2, this is probably solved too.

**Comment by haroldadmin** [comment]
Thank you for reporting this. I'll solve this in the next release.

**Comment by haroldadmin** [comment]
Fixed via [this](https://github.com/haroldadmin/MovieDB/commit/0aa4e73432874869686c3dedff4fed023295fa39)
