### ISSUE TITLE
The youtube player's maximize button is broken

### ISSUE THREAD

**Issue by carstenhag** [haroldadmin/MovieDB#7]
Somehow it makes the player grow vertically a lot, and then there's weird behavior. I'd suggest to always open the native yt app, but eh, just fixing this is good too. 

https://drive.google.com/file/d/1wDT58QezV4z7yPN0v5IsFnZAwiLtgdZi/view?usp=drivesdk

**Comment by haroldadmin** [comment]
Thank you for documenting this. I am aware of this issue, and I have been wondering whether I should even include trailers in the details page. The youtube player is embedded in a recycler view, so it is going to be a little harder than usual to make it go fullscreen.

Would you be interested in working on this?

**Comment by haroldadmin** [comment]
The Youtube Trailers feature has been removed from the app because Google Play complains about policy violations.
